# Don't print a new line at the start of the prompt
add_newline = false

# Make prompt a single line instead of two lines
[line_break]
disabled = true

# Replace the "❯" symbol in the prompt with "➜"
[character]
# The "success_symbol" segment is being set to "➜" with the color "bold green"
# use_symbol_for_status = true
success_symbol = "[➜](bold green)"
error_symbol = "[✖](bold red)"

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

# configure directory
[directory]
truncation_length = 1
format = "[$path]($style)[$read_only]($read_only_style) "

[cmd_duration]
format = "took [$duration]($style) "
style = "bold yellow"
disabled = false

[env_var]
format = "with [$env_value]($style) "

[time]
time_format = "%T"
format = "at 🕙[$time]($style) "

[battery]
full_symbol = "🔋"
charging_symbol = "⚡️"
discharging_symbol = "💀"

[[battery.display]]  # "bold red" style when capacity is between 0% and 10%
threshold = 10
style = "bold red"

[[battery.display]]  # "bold yellow" style when capacity is between 10% and 30%
threshold = 30
style = "bold yellow"

[username]
style_user = "bold yellow"
style_root = "bold green"
format = "[$user]($style) on "
disabled = false
show_always = true

[status]
style = "bg:black"
symbol = "🔴"
format = '[\[$symbol $common_meaning$signal_name$maybe_int\]]($style) '
map_symbol = true
disabled = false

[dart]
format = "via [🔰 $version](bold red) "

[docker_context]
format = "via [🐋 $context](blue bold)"

[nodejs]
format = "via [🤖 $version](bold green) "

[rust]
format = "via [⚙️ $version](red bold)"

[gcloud]
disabled = true